name: Eames
favicon: null
layout_spectrum: 0.4201965711545199
typography_spectrum: 0.3011551066301763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#040404'
    - '#cbbead'
    - '#4a4418'
    - '#646f24'
  brandStrength: 0.1875
  lightness: 0.70245675672777
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
