name: Eames
favicon: null
layout_spectrum: 0.4201965711545199
typography_spectrum: 0.3011551066301763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9847257775254548
  lightness: 0.70245675672777
  saturation: 0.20943452580831945
  rhythmicContrast: 0.05324809974990785
purpose: []
